name: QA - CSS Lints

on:
  push:
    paths:
      - 'qa-tester/**'
    branches:
      - master
      - develop
      # Include all release branches.
      - '[0-9].[0-9]'
  pull_request:

defaults:
  run:
    working-directory: qa-tester

jobs:
  lint:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Configure npm cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Node dependencies
        run: npm ci
        env:
          CI: true

      - name: Detect coding standard violations (stylelint)
        run: npm run lint:css
